// examples/nuxt/pages/index.vue
<template>
  <nav>
    <ul>
      <li><NuxtLink to="./mux-video" class="video">&lt;mux-video&gt;</NuxtLink></li>
      <li><NuxtLink to="./mux-audio" class="audio">&lt;mux-audio&gt;</NuxtLink></li>
      <li><NuxtLink to="./mux-player" class="player">&lt;mux-player&gt;</NuxtLink></li>
    </ul>
  </nav>
</template>

// examples/create-react-app-with-typescript/src/pages/index.tsx
import { Link } from "react-router-dom";

function Home() {
  return (
    <nav>
      <ul>
        <li><Link to="./MuxVideo" className="video">&lt;MuxVideo&gt;</Link></li>
        <li><Link to="./MuxAudio" className="audio">&lt;MuxAudio&gt;</Link></li>
        <li><Link to="./MuxPlayer" className="player">&lt;MuxPlayer&gt;</Link></li>
        <li><Link to="./MuxUploader" className="uploader">&lt;MuxUploader&gt;</Link></li>
      </ul>
    </nav>
  );
}

export default Home;
