// examples/nuxt/pages/mux-audio.vue
<script>
import "@mux/mux-audio";
</script>

<style>
mux-audio {
  width: 100%;
  margin: 1rem 0 2rem;
}
</style>

<template>
  <mux-audio
    playback-id="vDpm5ygrRJgfIEPNIc02IJR4Trf3z00AiP"
    metadata-video-id="episode-id-12345"
    metadata-video-title="Podcast: Episode 3"
    metadata-viewer-user-id="user-id-6789"
    muted
    controls
  ></mux-audio>

  <NuxtLink to="/">Browse Elements</NuxtLink>
</template>

// examples/create-react-app-with-typescript/src/pages/MuxAudio.tsx
import { Link } from "react-router-dom";
import MuxAudio from "@mux/mux-audio-react";

function MuxAudioPage() {
  return (
    <>
      <style>
        {`audio {
          width: 100%;
          margin: 1rem 0 2rem;
        }`}
      </style>

      <MuxAudio
        playbackId="DS00Spx1CV902MCtPj5WknGlR102V5HFkDe"
        controls
        muted
      />

      <Link to="/">Browse Elements</Link>
    </>
  );
}

export default MuxAudioPage;
