// examples/create-react-app-with-typescript/src/pages/MuxPlayer.tsx
/* eslint-disable @typescript-eslint/no-unused-vars */
import { Link } from "react-router-dom";
import MuxPlayer from "@mux/mux-player-react";
import { useRef, useState } from "react";

function MuxPlayerPage() {
  return (
    <>
      <style>
        {`mux-player {
          display: block;
          width: 100%;
          aspect-ratio: 16 / 9;
          margin: 1rem 0 2rem;
        }`}
      </style>

      <MuxPlayer
        playbackId="23s11nz72DsoN657h4314PjKKjsF2JG33eBQQt6B95I"
        metadata={{
          video_id: "video-id-12345",
          video_title: "Star Wars: Episode 3",
          viewer_user_id: "user-id-6789",
        }}
        streamType="on-demand"
        muted
      />

      <Link to="/">Browse Elements</Link>
    </>
  );
}

export default MuxPlayerPage;

// examples/nuxt/pages/mux-player.vue
<script>
import "@mux/mux-player";
</script>

<style>
mux-player {
  display: block;
  width: 100%;
  margin: 1rem 0 2rem;
  background-color: #000;
  line-height: 0;
}

mux-player:not([audio]) {
  aspect-ratio: 16 / 9;
}
</style>

<template>
  <mux-player
    stream-type="on-demand"
    playback-id="23s11nz72DsoN657h4314PjKKjsF2JG33eBQQt6B95I"
  ></mux-player>

  <NuxtLink to="/">Browse Elements</NuxtLink>
</template>
